export const schools = [
  {
    id: "lincoln-elem",
    name: "Lincoln Elementary School",
    address: "615 W Armitage Ave, Chicago, IL",
    neighborhood: "Lincoln Park",
    distanceMiles: 1.8,
    rating: 8.3,
    preK: true,
    startGrade: "Pre-K",
    publicType: "Public",
    selective: false,
    deadline: "2025-01-15",
    schoolType: "Neighborhood CPS",
    enrollment: "Open enrollment with sibling preference.",
    applicationInstructions:
      "Submit the online CPS application, upload proof of residency, and attend a tour or information session.",
    programHighlights: [
      "Dual-language Spanish program",
      "On-site early childhood center",
      "After-school enrichment with partner nonprofits",
    ],
  },
  {
    id: "chicago-classical",
    name: "Chicago Classical Magnet School",
    address: "1234 N Sedgwick St, Chicago, IL",
    neighborhood: "Old Town",
    distanceMiles: 2.4,
    rating: 9.1,
    preK: false,
    startGrade: "K",
    publicType: "Public",
    selective: true,
    deadline: "2024-12-10",
    schoolType: "Magnet CPS",
    enrollment: "Citywide lottery with academic screening.",
    applicationInstructions:
      "Complete the CPS Selective Enrollment application, submit test scores if available, and rank the school in your top choices.",
    programHighlights: [
      "Classical curriculum with Latin",
      "Accelerated math starting in grade 2",
      "Dedicated arts and music wing",
    ],
  },
  {
    id: "lakeside-montessori",
    name: "Lakeside Montessori Academy",
    address: "2450 N Halsted St, Chicago, IL",
    neighborhood: "Lakeview",
    distanceMiles: 1.2,
    rating: 7.6,
    preK: true,
    startGrade: "Pre-K",
    publicType: "Private",
    selective: false,
    deadline: "2025-02-20",
    schoolType: "Independent Private",
    enrollment: "Rolling admissions with school visit.",
    applicationInstructions:
      "Schedule a classroom observation, submit the private school application, and complete the family interview.",
    programHighlights: [
      "Authentic Montessori materials",
      "Mixed-age classrooms",
      "Extended-day options",
    ],
  },
  {
    id: "north-park-gifted",
    name: "North Park Regional Gifted Center",
    address: "5801 N Pulaski Rd, Chicago, IL",
    neighborhood: "North Park",
    distanceMiles: 6.5,
    rating: 9.4,
    preK: false,
    startGrade: "K",
    publicType: "Public",
    selective: true,
    deadline: "2024-11-30",
    schoolType: "Regional Gifted CPS",
    enrollment: "Testing and placement required.",
    applicationInstructions:
      "Register for CPS Gifted Center testing, submit the application by the deadline, and attend the placement meeting if invited.",
    programHighlights: [
      "Gifted curriculum with project-based learning",
      "STEM lab and robotics",
      "Transportation available for eligible families",
    ],
  },
  {
    id: "south-loop-charter",
    name: "South Loop Charter School",
    address: "1200 S State St, Chicago, IL",
    neighborhood: "South Loop",
    distanceMiles: 3.1,
    rating: 7.2,
    preK: true,
    startGrade: "Pre-K",
    publicType: "Public",
    selective: false,
    deadline: "2025-03-01",
    schoolType: "Charter",
    enrollment: "Open lottery with sibling preference.",
    applicationInstructions:
      "Submit the charter application, attend the family information night, and confirm enrollment within 7 days of offer.",
    programHighlights: [
      "Reggio-inspired early childhood rooms",
      "Community partnership programming",
      "Family volunteer program",
    ],
  },
  {
    id: "hyde-park-academy",
    name: "Hyde Park Prep Academy",
    address: "5125 S Cornell Ave, Chicago, IL",
    neighborhood: "Hyde Park",
    distanceMiles: 7.9,
    rating: 8.7,
    preK: false,
    startGrade: "K",
    publicType: "Private",
    selective: true,
    deadline: "2025-01-05",
    schoolType: "Independent Private",
    enrollment: "Interview and readiness assessment required.",
    applicationInstructions:
      "Complete the private school application, schedule an assessment, and submit recommendation letters.",
    programHighlights: [
      "STEAM-focused classrooms",
      "Global language immersion",
      "Athletics and arts electives",
    ],
  },
];
