export const schools = [
  {
    id: "abraham-lincoln",
    name: "Abraham Lincoln Elementary School",
    address: "615 W Kemper Pl, Chicago, IL 60614",
    neighborhood: "Lincoln Park",
    latitude: null,
    longitude: null,
    greatSchoolsRating: 9,
    nicheRating: "A",
    startGrade: "K",
    endGrade: "8",
    preK: false,
    publicType: "Public",
    selective: false,
    deadline: "2025-12-05",
    schoolType: "Neighborhood",
    tuition: "N/A (public)",
    enrollment: "~803 students",
    studentTeacherRatio: "~16:1",
    applicationInstructions:
      "Neighborhood residents have guaranteed seats. Out-of-boundary families can apply via the GoCPS lottery (typically early December).",
    programHighlights: [
      "Strong academics with CPS Exemplary rating",
      "Arts, language, and technology programs",
      "Active PTA and community fundraising",
    ],
  },
  {
    id: "alcott",
    name: "Louisa May Alcott Elementary School",
    address: "2625 N Orchard St, Chicago, IL 60614",
    neighborhood: "Lincoln Park",
    latitude: null,
    longitude: null,
    greatSchoolsRating: 10,
    nicheRating: "A-",
    startGrade: "PK3",
    endGrade: "8",
    preK: true,
    publicType: "Public",
    selective: false,
    deadline: "2025-12-05",
    schoolType: "Neighborhood",
    tuition: "N/A (public)",
    enrollment: "~575 students",
    studentTeacherRatio: "13:1",
    applicationInstructions:
      "Neighborhood seats are guaranteed. Families outside the boundary can apply via the GoCPS lottery in December.",
    programHighlights: [
      "Project Lead The Way STEM program",
      "Gifted and enrichment offerings",
      "Whole-child academic and social-emotional support",
    ],
  },
  {
    id: "oscar-mayer",
    name: "Oscar Mayer Magnet School",
    address: "2250 N Clifton Ave, Chicago, IL 60614",
    neighborhood: "Lincoln Park",
    latitude: null,
    longitude: null,
    greatSchoolsRating: 8,
    nicheRating: "A-",
    startGrade: "PK3",
    endGrade: "8",
    preK: true,
    publicType: "Public",
    selective: false,
    deadline: "2025-12-05",
    schoolType: "Magnet (Montessori + IB)",
    tuition: "N/A (public)",
    enrollment: "~740 students",
    studentTeacherRatio: "~14:1",
    applicationInstructions:
      "Apply through the GoCPS lottery for magnet seats. Neighborhood and sibling priority apply.",
    programHighlights: [
      "Montessori program in early grades",
      "International Baccalaureate MYP for grades 6–8",
      "Fine & Performing Arts integration",
    ],
  },
  {
    id: "newberry",
    name: "Newberry Math & Science Academy",
    address: "700 W Willow St, Chicago, IL 60614",
    neighborhood: "Near North / Old Town",
    latitude: null,
    longitude: null,
    greatSchoolsRating: 7,
    nicheRating: "A-",
    startGrade: "K",
    endGrade: "8",
    preK: false,
    publicType: "Public",
    selective: false,
    deadline: "2025-12-05",
    schoolType: "Magnet (STEM)",
    tuition: "N/A (public)",
    enrollment: "~400 students",
    studentTeacherRatio: "~13:1",
    applicationInstructions:
      "Apply via GoCPS lottery (no attendance boundary). Sibling priority applies.",
    programHighlights: [
      "STEM-focused inquiry curriculum",
      "Science labs and technology resources",
      "Accelerated math options",
    ],
  },
  {
    id: "franklin-fine-arts",
    name: "Franklin Fine Arts Center",
    address: "225 W Evergreen Ave, Chicago, IL 60610",
    neighborhood: "Old Town",
    latitude: null,
    longitude: null,
    greatSchoolsRating: 7,
    nicheRating: "A-",
    startGrade: "K",
    endGrade: "8",
    preK: false,
    publicType: "Public",
    selective: false,
    deadline: "2025-12-05",
    schoolType: "Magnet (Fine & Performing Arts)",
    tuition: "N/A (public)",
    enrollment: "~350 students",
    studentTeacherRatio: "~12:1",
    applicationInstructions:
      "Apply through the GoCPS magnet lottery. No audition required for elementary entry.",
    programHighlights: [
      "Visual art, music, drama, and dance integration",
      "Citywide lottery admissions",
      "Small, arts-focused community",
    ],
  },
  {
    id: "lasalle-language",
    name: "LaSalle Language Academy",
    address: "1734 N Orleans St, Chicago, IL 60614",
    neighborhood: "Old Town",
    latitude: null,
    longitude: null,
    greatSchoolsRating: 8,
    nicheRating: "A-",
    startGrade: "K",
    endGrade: "8",
    preK: false,
    publicType: "Public",
    selective: false,
    deadline: "2025-12-05",
    schoolType: "Magnet (World Language)",
    tuition: "N/A (public)",
    enrollment: "~483 students",
    studentTeacherRatio: "12:1",
    applicationInstructions:
      "Apply via GoCPS lottery. Sibling, staff, proximity, and tier priorities apply.",
    programHighlights: [
      "Daily world language instruction",
      "Strong academic performance",
      "International cultural programming",
    ],
  },
  {
    id: "skinner-north",
    name: "Skinner North Classical School",
    address: "640 W Scott St, Chicago, IL 60610",
    neighborhood: "Near North",
    latitude: null,
    longitude: null,
    greatSchoolsRating: 8,
    nicheRating: "A-",
    startGrade: "K",
    endGrade: "8",
    preK: false,
    publicType: "Public",
    selective: true,
    deadline: "2025-12-05",
    schoolType: "Selective Enrollment Classical",
    tuition: "N/A (public)",
    enrollment: "~480 students",
    studentTeacherRatio: "~16:1",
    applicationInstructions:
      "Apply through GoCPS selective enrollment. Entrance exam is required in fall 2025.",
    programHighlights: [
      "Accelerated classical curriculum",
      "Citywide competitive admissions",
      "Strong arts, language, and humanities",
    ],
  },
  {
    id: "blaine",
    name: "James G. Blaine Elementary School",
    address: "1420 W Grace St, Chicago, IL 60613",
    neighborhood: "Lakeview",
    latitude: null,
    longitude: null,
    greatSchoolsRating: 8,
    nicheRating: "A-",
    startGrade: "PK4",
    endGrade: "8",
    preK: true,
    publicType: "Public",
    selective: false,
    deadline: "2025-12-05",
    schoolType: "Neighborhood (Magnet Cluster - Literature & Writing)",
    tuition: "N/A (public)",
    enrollment: "~636 students",
    studentTeacherRatio: "12:1",
    applicationInstructions:
      "Neighborhood seats are guaranteed. Out-of-boundary families can apply via GoCPS lottery if space allows.",
    programHighlights: [
      "Literature and writing focus",
      "Strong test performance",
      "Active parent organizations and enrichment",
    ],
  },
  {
    id: "nettelhorst",
    name: "Nettelhorst Elementary School",
    address: "3252 N Broadway, Chicago, IL 60657",
    neighborhood: "East Lakeview",
    latitude: null,
    longitude: null,
    greatSchoolsRating: 9,
    nicheRating: "A-",
    startGrade: "PK3",
    endGrade: "8",
    preK: true,
    publicType: "Public",
    selective: false,
    deadline: "2025-12-05",
    schoolType: "Neighborhood (Magnet Cluster - Fine & Performing Arts)",
    tuition: "N/A (public)",
    enrollment: "~650 students",
    studentTeacherRatio: "14:1",
    applicationInstructions:
      "Neighborhood students are guaranteed. Out-of-boundary families apply via GoCPS lottery.",
    programHighlights: [
      "Fine arts integration",
      "Community garden and student-run farmers market",
      "French language in upper grades",
    ],
  },
  {
    id: "hawthorne",
    name: "Hawthorne Scholastic Academy",
    address: "3319 N Clifton Ave, Chicago, IL 60657",
    neighborhood: "Lakeview",
    latitude: null,
    longitude: null,
    greatSchoolsRating: 10,
    nicheRating: "A",
    startGrade: "K",
    endGrade: "8",
    preK: false,
    publicType: "Public",
    selective: false,
    deadline: "2025-12-05",
    schoolType: "Magnet (Scholastic Academy)",
    tuition: "N/A (public)",
    enrollment: "~604 students",
    studentTeacherRatio: "~15:1",
    applicationInstructions:
      "Apply via GoCPS magnet lottery. Sibling and proximity priorities apply.",
    programHighlights: [
      "Rigorous curriculum and enrichment",
      "Gifted/talented programming",
      "Extensive sports and arts offerings",
    ],
  },
  {
    id: "bell",
    name: "Alexander Graham Bell Elementary School",
    address: "3730 N Oakley Ave, Chicago, IL 60618",
    neighborhood: "North Center",
    latitude: null,
    longitude: null,
    greatSchoolsRating: 10,
    nicheRating: "A-",
    startGrade: "K",
    endGrade: "8",
    preK: false,
    publicType: "Public",
    selective: true,
    deadline: "2025-12-05",
    schoolType: "Neighborhood + Regional Gifted Center",
    tuition: "N/A (public)",
    enrollment: "~848 students",
    studentTeacherRatio: "15:1",
    applicationInstructions:
      "Neighborhood K seats are open for local residents. Regional Gifted Center seats require testing via GoCPS.",
    programHighlights: [
      "Regional Gifted Center program",
      "Strong arts and extracurriculars",
      "Specialized deaf/hard-of-hearing track",
    ],
  },
  {
    id: "coonley",
    name: "John C. Coonley Elementary School",
    address: "4046 N Leavitt St, Chicago, IL 60618",
    neighborhood: "North Center",
    latitude: null,
    longitude: null,
    greatSchoolsRating: 9,
    nicheRating: "A",
    startGrade: "K",
    endGrade: "8",
    preK: false,
    publicType: "Public",
    selective: true,
    deadline: "2025-12-05",
    schoolType: "Neighborhood + Regional Gifted Center",
    tuition: "N/A (public)",
    enrollment: "~1,200 students",
    studentTeacherRatio: "~17:1",
    applicationInstructions:
      "Neighborhood seats are open to residents. Regional Gifted Center seats require GoCPS testing and application.",
    programHighlights: [
      "STEAM labs and maker spaces",
      "National Blue Ribbon recognition",
      "Robust fine arts program",
    ],
  },
  {
    id: "pulaski",
    name: "Pulaski International School of Chicago",
    address: "2230 W McLean Ave, Chicago, IL 60647",
    neighborhood: "Bucktown",
    latitude: null,
    longitude: null,
    greatSchoolsRating: 6,
    nicheRating: "B+",
    startGrade: "PK4",
    endGrade: "8",
    preK: true,
    publicType: "Public",
    selective: false,
    deadline: "2025-12-05",
    schoolType: "Neighborhood (IB PYP)",
    tuition: "N/A (public)",
    enrollment: "~600 students",
    studentTeacherRatio: "~16:1",
    applicationInstructions:
      "Neighborhood seats are guaranteed. Out-of-boundary families can apply via GoCPS lottery for IB and gifted programs.",
    programHighlights: [
      "International Baccalaureate PYP",
      "Spanish language instruction",
      "Bilingual gifted program for EL students",
    ],
  },
  {
    id: "drummond",
    name: "Drummond Montessori School",
    address: "1845 W Cortland St, Chicago, IL 60622",
    neighborhood: "Bucktown",
    latitude: null,
    longitude: null,
    greatSchoolsRating: 7,
    nicheRating: "A-",
    startGrade: "PK3",
    endGrade: "8",
    preK: true,
    publicType: "Public",
    selective: false,
    deadline: "2025-12-05",
    schoolType: "Magnet (Montessori)",
    tuition: "N/A (public)",
    enrollment: "~350 students",
    studentTeacherRatio: "~11:1",
    applicationInstructions:
      "Apply via GoCPS magnet lottery. Montessori program is citywide with sibling priority.",
    programHighlights: [
      "Authentic Montessori multi-age classrooms",
      "Hands-on, self-directed learning",
      "Strong parent satisfaction",
    ],
  },
  {
    id: "burr",
    name: "Jonathan Burr Elementary School",
    address: "1621 W Wabansia Ave, Chicago, IL 60622",
    neighborhood: "Bucktown",
    latitude: null,
    longitude: null,
    greatSchoolsRating: 5,
    nicheRating: "B",
    startGrade: "K",
    endGrade: "8",
    preK: false,
    publicType: "Public",
    selective: false,
    deadline: "2025-12-05",
    schoolType: "Neighborhood (Magnet Cluster - Fine Arts & Technology)",
    tuition: "N/A (public)",
    enrollment: "~400 students",
    studentTeacherRatio: "~14:1",
    applicationInstructions:
      "Neighborhood seats are open to residents. Out-of-boundary families can apply via GoCPS lottery if space allows.",
    programHighlights: [
      "Arts-integrated curriculum",
      "Dual-language Spanish program",
      "Community service and SEL focus",
    ],
  },
  {
    id: "pritzker",
    name: "A.N. Pritzker School",
    address: "2009 W Schiller St, Chicago, IL 60622",
    neighborhood: "Wicker Park",
    latitude: null,
    longitude: null,
    greatSchoolsRating: 7,
    nicheRating: "A-",
    startGrade: "K",
    endGrade: "8",
    preK: false,
    publicType: "Public",
    selective: true,
    deadline: "2025-12-05",
    schoolType: "Neighborhood + Magnet + Regional Gifted Center",
    tuition: "N/A (public)",
    enrollment: "~700 students",
    studentTeacherRatio: "~16:1",
    applicationInstructions:
      "Neighborhood seats are open to local residents. Magnet and RGC seats require GoCPS lottery/testing.",
    programHighlights: [
      "Fine & Performing Arts magnet",
      "Regional Gifted Center program",
      "Robust after-school arts offerings",
    ],
  },
  {
    id: "lasalle-ii",
    name: "LaSalle II Magnet School",
    address: "1148 N Honore St, Chicago, IL 60622",
    neighborhood: "Wicker Park",
    latitude: null,
    longitude: null,
    greatSchoolsRating: 6,
    nicheRating: "A-",
    startGrade: "PK4",
    endGrade: "8",
    preK: true,
    publicType: "Public",
    selective: false,
    deadline: "2025-12-05",
    schoolType: "Magnet (World Language)",
    tuition: "N/A (public)",
    enrollment: "~600 students",
    studentTeacherRatio: "13:1",
    applicationInstructions:
      "Apply via GoCPS lottery for citywide magnet seats.",
    programHighlights: [
      "World language immersion options",
      "Global studies focus",
      "Improving test performance",
    ],
  },
  {
    id: "parker",
    name: "Francis W. Parker School",
    address: "330 W Webster Ave, Chicago, IL 60614",
    neighborhood: "Lincoln Park",
    latitude: null,
    longitude: null,
    greatSchoolsRating: null,
    nicheRating: "A+",
    startGrade: "JK",
    endGrade: "12",
    preK: true,
    publicType: "Private",
    selective: true,
    deadline: "2025-11-21",
    schoolType: "Independent (College-Prep)",
    tuition: "$43,590–$48,700+",
    enrollment: "~940 students (JK–12)",
    studentTeacherRatio: "8:1",
    applicationInstructions:
      "Submit the private school application, schedule parent interviews, and complete student assessments by the November deadline.",
    programHighlights: [
      "Progressive, inquiry-based curriculum",
      "Extensive arts and STEAM resources",
      "Significant financial aid availability",
    ],
  },
  {
    id: "latin",
    name: "Latin School of Chicago",
    address: "59 W North Blvd, Chicago, IL 60610",
    neighborhood: "Gold Coast",
    latitude: null,
    longitude: null,
    greatSchoolsRating: null,
    nicheRating: "A+",
    startGrade: "JK",
    endGrade: "12",
    preK: true,
    publicType: "Private",
    selective: true,
    deadline: "2025-11-26",
    schoolType: "Independent (College-Prep)",
    tuition: "$40,090+",
    enrollment: "~1,190 students (JK–12)",
    studentTeacherRatio: "~8:1",
    applicationInstructions:
      "Apply through Latin’s admissions process, including assessments and family interviews by the published deadlines.",
    programHighlights: [
      "Rigorous academics and enrichment",
      "Strong world language and arts programming",
      "Extensive campus facilities",
    ],
  },
  {
    id: "bisc",
    name: "British International School of Chicago, Lincoln Park",
    address: "814 W Eastman St, Chicago, IL 60642",
    neighborhood: "Lincoln Park",
    latitude: null,
    longitude: null,
    greatSchoolsRating: null,
    nicheRating: "A",
    startGrade: "Nursery",
    endGrade: "5",
    preK: true,
    publicType: "Private",
    selective: false,
    deadline: "2026-02-01",
    schoolType: "International (British Curriculum)",
    tuition: "$20,000–$32,000",
    enrollment: "~300 students",
    studentTeacherRatio: "~7:1–10:1",
    applicationInstructions:
      "Rolling admissions. Schedule a tour, submit the application, and complete student readiness review.",
    programHighlights: [
      "International Primary Curriculum",
      "Global learning and language programs",
      "Nord Anglia network resources",
    ],
  },
  {
    id: "near-north-montessori",
    name: "Near North Montessori School",
    address: "1434 W Division St, Chicago, IL 60642",
    neighborhood: "Wicker Park",
    latitude: null,
    longitude: null,
    greatSchoolsRating: null,
    nicheRating: "A",
    startGrade: "Toddler",
    endGrade: "8",
    preK: true,
    publicType: "Private",
    selective: false,
    deadline: "2026-01-15",
    schoolType: "Independent (Montessori)",
    tuition: "$18,300–$25,250",
    enrollment: "~585 students",
    studentTeacherRatio: "7:1",
    applicationInstructions:
      "Apply by the January priority deadline, schedule classroom observation, and complete family interview.",
    programHighlights: [
      "Authentic Montessori multi-age classrooms",
      "Urban campus with specialty spaces",
      "Strong community traditions",
    ],
  },
  {
    id: "catherine-cook",
    name: "The Catherine Cook School",
    address: "226 W Schiller St, Chicago, IL 60610",
    neighborhood: "Old Town",
    latitude: null,
    longitude: null,
    greatSchoolsRating: null,
    nicheRating: "A",
    startGrade: "Preschool",
    endGrade: "8",
    preK: true,
    publicType: "Private",
    selective: true,
    deadline: "2026-01-12",
    schoolType: "Independent (Elementary & Middle)",
    tuition: "$19,980–$33,400",
    enrollment: "~570 students",
    studentTeacherRatio: "~9:1",
    applicationInstructions:
      "Apply by the January deadline, attend a tour/playdate, and complete student assessments.",
    programHighlights: [
      "Project-based, interdisciplinary curriculum",
      "Technology and makerspace integration",
      "Character education focus",
    ],
  },
  {
    id: "st-clement",
    name: "St. Clement School",
    address: "2524 N Orchard St, Chicago, IL 60614",
    neighborhood: "Lincoln Park",
    latitude: null,
    longitude: null,
    greatSchoolsRating: null,
    nicheRating: "A",
    startGrade: "PK3",
    endGrade: "8",
    preK: true,
    publicType: "Private",
    selective: false,
    deadline: "2026-01-10",
    schoolType: "Parochial (Catholic)",
    tuition: "$11,800–$13,000",
    enrollment: "~470 students",
    studentTeacherRatio: "~18:1",
    applicationInstructions:
      "Priority registration for parish families, followed by rolling admissions if space remains.",
    programHighlights: [
      "Faith-based academics and service",
      "Spanish, art, music, and tech classes",
      "Strong parish community",
    ],
  },
  {
    id: "st-josaphat",
    name: "St. Josaphat School",
    address: "2245 N Southport Ave, Chicago, IL 60614",
    neighborhood: "Lincoln Park",
    latitude: null,
    longitude: null,
    greatSchoolsRating: null,
    nicheRating: "A-",
    startGrade: "PK3",
    endGrade: "8",
    preK: true,
    publicType: "Private",
    selective: false,
    deadline: "2026-02-01",
    schoolType: "Parochial (Catholic)",
    tuition: "$10,500–$11,500",
    enrollment: "~300 students",
    studentTeacherRatio: "~15:1",
    applicationInstructions:
      "Apply by February with parish priority. Schedule a family tour and student visit.",
    programHighlights: [
      "Family-like school culture",
      "Chromebook program for middle school",
      "CYO sports and enrichment clubs",
    ],
  },
  {
    id: "chicago-city-day",
    name: "Chicago City Day School",
    address: "310 W Irving Park Rd, Chicago, IL 60613",
    neighborhood: "Lakeview",
    latitude: null,
    longitude: null,
    greatSchoolsRating: null,
    nicheRating: "A",
    startGrade: "JK",
    endGrade: "8",
    preK: true,
    publicType: "Private",
    selective: true,
    deadline: "2026-01-15",
    schoolType: "Independent (Elementary & Middle)",
    tuition: "$29,800",
    enrollment: "~300 students",
    studentTeacherRatio: "~7:1",
    applicationInstructions:
      "Apply by January, schedule a student observation, and complete family interviews.",
    programHighlights: [
      "Experiential learning with campus gardens",
      "Low student-teacher ratios",
      "Strong arts and language enrichment",
    ],
  },
];
